export const ProductService = {
    getProductsData() {
        return [
          
            {
                employeeId: "1001",
                employeeCode: "x45uvw6y",
                employeeName: "Olivia Martinez",
                department: "Sales",
                designation: "sales manager",
                employeeImage: "olivia-martinez.jpg",
                employeeSalary: 75000,
                employeeDepartment: "Sales",
                employeeStatus: "ACTIVE",
                employeeRating: 4.7,
                joinDate: "2024-02-14T09:00:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                workedhours:'9 hrs',
                scheduledhours :'8 hrs',

              },
              {
                employeeId: "1002",
                employeeCode: "b12cd34e",
                employeeName: "Daniel Taylor",
                department: "IT",
                designation: "software engineer",
                employeeImage: "daniel-taylor.jpg",
                employeeSalary: 67000,
                employeeDepartment: "HR",
                employeeStatus: "ACTIVE",
                employeeRating: 4.4,
                joinDate: "2024-02-15T10:30:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                workedhours:'9 hrs',
                scheduledhours :'8 hrs',
              },


              {
                employeeId: "1003",
                employeeCode: "d56efg7h",
                employeeName: "Liam Turner",
                department: "Marketing",
                designation: "marketing specialist",
                employeeImage: "liam-turner.jpg",
                employeeSalary: 60000,
                employeeDepartment: "Marketing",
                employeeStatus: "ACTIVE",
                employeeRating: 4.2,
                joinDate: "2024-02-19T09:30:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                workedhours:'9 hrs',
                scheduledhours :'8 hrs',
              },
              {
                employeeId: "1004",
                employeeCode: "y89hij0k",
                employeeName: "Ella Baker",
                department: "IT",
                designation: "software developer",
                employeeImage: "ella-baker.jpg",
                employeeSalary: 68000,
                employeeDepartment: "HR",
                employeeStatus: "ACTIVE",
                employeeRating: 4.8,
                joinDate: "2024-02-20T11:45:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                workedhours:'9 hrs',
                scheduledhours :'8 hrs',
              },
              {
                employeeId: "1005",
                employeeCode: "l23mno4p",
                employeeName: "Logan Davis",
                department: "Finance",
                designation: "financial analyst",
                employeeImage: "logan-davis.jpg",
                employeeSalary: 72000,
                employeeDepartment: "Finance",
                employeeStatus: "ACTIVE",
                employeeRating: 4.9,
                joinDate: "2024-02-21T13:00:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                workedhours:'9 hrs',
                scheduledhours :'8 hrs',
              },
              {
                employeeId: "1006",
                employeeCode: "s45tuv6w",
                employeeName: "Ava Johnson",
                department: "Sales",
                designation: "sales representative",
                employeeImage: "ava-johnson.jpg",
                employeeSalary: 62000,
                employeeDepartment: "Sales",
                employeeStatus: "ACTIVE",
                employeeRating: 4.5,
                joinDate: "2024-02-22T14:15:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                workedhours:'9 hrs',
                scheduledhours :'8 hrs',
              },
              {
                employeeId: "1007",
                employeeCode: "z12abc3d",
                employeeName: "Mia White",
                department: "Marketing",
                designation: "marketing coordinator",
                employeeImage: "mia-white.jpg",
                employeeSalary: 61000,
                employeeDepartment: "Marketing",
                employeeStatus: "ACTIVE",
                employeeRating: 4.6,
                joinDate: "2024-02-23T16:30:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                workedhours:'9 hrs',
                scheduledhours :'8 hrs',
              },
              {
                employeeId: "1008",
                employeeCode: "u78vwx9y",
                employeeName: "Noah Harris",
                department: "IT",
                designation: "system administrator",
                employeeImage: "noah-harris.jpg",
                employeeSalary: 70000,
                employeeDepartment: "HR",
                employeeStatus: "ACTIVE",
                employeeRating: 4.7,
                joinDate: "2024-02-24T09:00:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                workedhours:'9 hrs',
                scheduledhours :'8 hrs',
              },
              {
                employeeId: "1009",
                employeeCode: "p45qrs6t",
                employeeName: "Isabella Turner",
                department: "Finance",
                designation: "financial planner",
                employeeImage: "isabella-turner.jpg",
                employeeSalary: 74000,
                employeeDepartment: "Finance",
                employeeStatus: "ACTIVE",
                employeeRating: 4.8,
                joinDate: "2024-02-25T10:30:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                workedhours:'9 hrs',
                scheduledhours :'8 hrs',
              },
              {
                employeeId: "1010",
                employeeCode: "w12xyz3a",
                employeeName: "James Adams",
                department: "Sales",
                designation: "sales coordinator",
                employeeImage: "james-adams.jpg",
                employeeSalary: 63000,
                employeeDepartment: "Sales",
                employeeStatus: "ACTIVE",
                employeeRating: 4.4,
                joinDate: "2024-02-26T12:45:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                checkintime:'9:00 AM',
                checkouttime:'6:00 PM',
                workedhours:'9 hrs',
                scheduledhours :'8 hrs',
              },
              {
                employeeId: "1011",
                employeeCode: "c67def8g",
                employeeName: "Abigail Baker",
                department: "IT",
                designation: "software engineer",
                employeeImage: "abigail-baker.jpg",
                employeeSalary: 67000,
                employeeDepartment: "HR",
                employeeStatus: "ACTIVE",
                employeeRating: 4.6,
                joinDate: "2024-02-27T14:00:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                checkintime:'9:00 AM',
                checkouttime:'6:00 PM',
                
                
              },
              {
                employeeId: "1012",
                employeeCode: "l34mno5p",
                employeeName: "Ethan Clark",
                department: "Marketing",
                designation: "marketing manager",
                employeeImage: "ethan-clark.jpg",
                employeeSalary: 77000,
                employeeDepartment: "Marketing",
                employeeStatus: "ACTIVE",
                employeeRating: 4.9,
                joinDate: "2024-02-28T16:15:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                checkintime:'9:00 AM',
                checkouttime:'6:00 PM',
              },
              {
                employeeId: "1013",
                employeeCode: "z78abc9d",
                employeeName: "Sophie Turner",
                department: "IT",
                designation: "systems analyst",
                employeeImage: "sophie-turner.jpg",
                employeeSalary: 69000,
                employeeDepartment: "HR",
                employeeStatus: "ACTIVE",
                employeeRating: 4.3,
                joinDate: "2024-03-01T09:45:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                checkintime:'9:00 AM',
                checkouttime:'6:00 PM',
              },
              {
                employeeId: "1014",
                employeeCode: "p23qrs4t",
                employeeName: "Aiden White",
                department: "Finance",
                designation: "financial analyst",
                employeeImage: "aiden-white.jpg",
                employeeSalary: 71000,
                employeeDepartment: "Finance",
                employeeStatus: "ACTIVE",
                employeeRating: 4.8,
                joinDate: "2024-03-02T11:30:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                checkintime:'9:00 AM',
                checkouttime:'6:00 PM',
              },
              {
                employeeId: "1015",
                employeeCode: "l89mno0p",
                employeeName: "Mia Johnson",
                department: "Sales",
                designation: "sales representative",
                employeeImage: "mia-johnson.jpg",
                employeeSalary: 63000,
                employeeDepartment: "Sales",
                employeeStatus: "ACTIVE",
                employeeRating: 4.5,
                joinDate: "2024-03-03T13:15:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                checkintime:'9:00 AM',
                checkouttime:'6:00 PM',
              },
              {
                employeeId: "1016",
                employeeCode: "r56stu7v",
                employeeName: "Lucas Baker",
                department: "IT",
                designation: "software engineer",
                employeeImage: "lucas-baker.jpg",
                employeeSalary: 68000,
                employeeDepartment: "HR",
                employeeStatus: "ACTIVE",
                employeeRating: 4.6,
                joinDate: "2024-03-04T14:30:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                checkintime:'9:00 AM',
                checkouttime:'6:00 PM',
              },
              {
                employeeId: "1017",
                employeeCode: "z12abc3d",
                employeeName: "Emma White",
                department: "Marketing",
                designation: "marketing coordinator",
                employeeImage: "emma-white.jpg",
                employeeSalary: 61000,
                employeeDepartment: "Marketing",
                employeeStatus: "ACTIVE",
                employeeRating: 4.7,
                joinDate: "2024-03-05T16:45:00Z",
                employeetype: "full-time",
                employeemobileno: "",
                bankname: "",
                bankaccountno: "",
                checkintime:'9:00 AM',
                checkouttime:'6:00 PM',
              }
            ];
        },
      };